### ISSUE TITLE
Update testing pkg.template from cpp-pm/hunter

### ISSUE THREAD

**Issue by hjmallon** [cpp-pm/hunter-testing#13]
I think the hunter-testing branch pkg.template needs updating from the hunter master branch. Currently when merging pr.* branches from cpp-pm hunter master into test.* branches there are merge conflicts.

To test. Where hunter_box_1 is some package to be updated.

```sh
git checkout master
git checkout -b pr.hunter_box_1

git checkout pkg.hunter_box_1
git pull

git checkout pkg.template
git pull
git checkout pkg.hunter_box_1
git merge pkg.template

# Last command has merge failures in README and .github folders.
```

**Comment by bkotzz** [comment]
I know this whole setup is pretty bad - we're trying to move away from it (see https://github.com/cpp-pm/hunter/issues/9) but it will take some time.

But a much simpler way of handling this is not merging that template branch in - instead just grabbing the files needed. All branches in this repo hold entire copies of hunter but all they really need is the travis and appveyor files.

What you can do is something like:
```
git checkout pkg.hunter_box_1
git fetch origin pkg.template
git checkout origin/pkg.template -- .travis.yml appveyor.yml
// Modify the paths from examples/foo in the template to examples/hunter_box_1
```

Let me know if that makes sense. I know we can document this stuff better but I think we're trying to use any time available to revamp the system rather than supporting the old one.

**Comment by hjmallon** [comment]
I have subbed to the other issue. I'm happy to close this.
